name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - run: yarn lint
    - run: yarn test:unit
    - run: yarn build 
    - run: ls -l
    - name: Deploy
      uses: docker://peaceiris/gh-pages:v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_PAT }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dist
